name: modern_titlebar_buttons
description: A package which provides most of the title bar buttons from windows, linux and macos. forked from titlebar_buttons
version: 1.1.1
repository: https://github.com/ArcaneArts/modern_titlebar_buttons
environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  dbus: ^0.7.11
  flutter_svg: ^2.0.17
  gsettings: ^0.2.8
  universal_io: ^2.2.2
  arcane: ^3.13.2+3
  change_case: 2.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/themes/adwaita/
    - assets/themes/arc-dark/
    - assets/themes/arc-light/
    - assets/themes/breeze/
    - assets/themes/elementary/
    - assets/themes/flat-remix/
    - assets/themes/materia-dark/
    - assets/themes/materia-light/
    - assets/themes/nordic/
    - assets/themes/osx-arc/
    - assets/themes/pop-dark/
    - assets/themes/pop-light/
    - assets/themes/unity-dark/
    - assets/themes/unity-light/
    - assets/themes/vimix/
    - assets/themes/yaru/
